name: Gradle Build & Publish to Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Entorno al que desplegar'
        type: choice
        options: [ 'development', 'production' ]
        required: true
        default: 'development'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    environment: ${{ github.event.inputs.environment || 'development' }}
    
    permissions:
      contents: 'read'
      id-token: 'write'

    env:

      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }} 
      GCP_LOCATION: ${{ vars.GCP_LOCATION }}
      GCP_REPOSITORY: ${{ vars.GCP_REPOSITORY }}

    steps:
      - name: ‚öôÔ∏è Checkout code
        uses: actions/checkout@v4
  
      - name: ‚ûï Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: üõ†Ô∏è Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' 
          cache: 'gradle'

      - name: üîê Authenticate to Google Cloud (WIF)
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/466181763387/locations/global/workloadIdentityPools/github-pool-v4/providers/github-provider'
          service_account: 'github-actions@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: üì¶ Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: üîë Get GCP Access Token
        id: get_token
        run: echo "token=$(gcloud auth print-access-token)" >> "$GITHUB_OUTPUT"

      - name: üì¶ Gradle Build & Run Tests
        run: ./gradlew build pitest -x publish

#      - name: üïµÔ∏è DEBUG - Verificar permisos de IAM
#        run: |
#          echo "Verificando la pol√≠tica de IAM para el repositorio ${{ env.GCP_REPOSITORY }}:"
#          gcloud artifacts repositories get-iam-policy ${{ env.GCP_REPOSITORY }} --location=${{ env.GCP_LOCATION }}

      - name: üì§ Publish to GAR
        run: ./gradlew publish
        env:
          gcpArtifactRegistryUsername: oauth2accesstoken
          gcpArtifactRegistryPassword: ${{ steps.get_token.outputs.token }}