name: Gradle Build & Publish to Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      
    env:
      GCP_PROJECT_ID: 'ethereal-brace-475715-d0'
      GCP_LOCATION: 'southamerica-west1'
      GCP_REPOSITORY: 'mvn-consalud'

    steps:
      - name: âš™ï¸ Checkout code
        uses: actions/checkout@v4
  
      - name: âž• Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: ðŸ› ï¸ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' 
          cache: 'gradle'

      - name: ðŸ” Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform'

      - name: ðŸ•µï¸ DEBUG - Verificar permisos de IAM
        run: |
          echo "Verificando la polÃ­tica de IAM para el repositorio ${{ env.GCP_REPOSITORY }}:"
          gcloud artifacts repositories get-iam-policy ${{ env.GCP_REPOSITORY }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --location=${{ env.GCP_LOCATION }} \
            --format=json

      - name: ðŸ”‘ Get GCP Access Token
        id: get_token
        run: echo "token=$(gcloud auth print-access-token)" >> "$GITHUB_OUTPUT"

      - name: ðŸ“¦ Gradle Build & Run Tests
        run: ./gradlew build pitest -x publish

      - name: ðŸ“¤ Publish to GAR
        run: ./gradlew publish
        env:
          gcpArtifactRegistryUsername: oauth2accesstoken 
          gcpArtifactRegistryPassword: ${{ steps.get_token.outputs.token }}
